version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: quotes-app-dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development