# Use Node.js 16 for development
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies using npm install
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose the development server port
EXPOSE 8080

# Start the development server
CMD ["npm", "run", "serve"]